CREATE INDEX idx_store_s_store_id ON dbo.store (s_store_id) INCLUDE (
	s_store_sk      
   ,s_rec_start_date  
   ,s_rec_end_date    
   ,s_closed_date_sk  
   ,s_store_name      
   ,s_number_employees
   ,s_floor_space     
   ,s_hours           
   ,s_manager         
   ,s_market_id       
   ,s_geography_class 
   ,s_market_desc     
   ,s_market_manager  
   ,s_division_id     
   ,s_division_name   
   ,s_company_id      
   ,s_company_name    
   ,s_street_number   
   ,s_street_name     
   ,s_street_type     
   ,s_suite_number    
   ,s_city            
   ,s_county          
   ,s_state           
   ,s_zip             
   ,s_country         
   ,s_gmt_offset      
   ,s_tax_precentage
)

CREATE INDEX idx_store_sales_s_store_sk ON dbo.store_sales (ss_store_sk) INCLUDE (
	ss_sold_date_sk       
   ,ss_sold_time_sk       
   ,ss_item_sk            
   ,ss_customer_sk        
   ,ss_cdemo_sk           
   ,ss_hdemo_sk           
   ,ss_addr_sk         
   ,ss_promo_sk           
   ,ss_ticket_number      
   ,ss_quantity           
   ,ss_wholesale_cost     
   ,ss_list_price         
   ,ss_sales_price        
   ,ss_ext_discount_amt   
   ,ss_ext_sales_price    
   ,ss_ext_wholesale_cost 
   ,ss_ext_list_price     
   ,ss_ext_tax            
   ,ss_coupon_amt         
   ,ss_net_paid           
   ,ss_net_paid_inc_tax   
   ,ss_net_profit
)

CREATE INDEX idx_store_returns_s_store_sk ON dbo.store_returns (sr_store_sk) INCLUDE (
    sr_returned_date_sk  
   ,sr_return_time_sk    
   ,sr_item_sk           
   ,sr_customer_sk       
   ,sr_cdemo_sk          
   ,sr_hdemo_sk          
   ,sr_addr_sk            
   ,sr_reason_sk         
   ,sr_ticket_number     
   ,sr_return_quantity   
   ,sr_return_amt        
   ,sr_return_tax        
   ,sr_return_amt_inc_tax
   ,sr_fee               
   ,sr_return_ship_cost  
   ,sr_refunded_cash     
   ,sr_reversed_charge   
   ,sr_store_credit      
   ,sr_net_loss          
)